name: Test GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "printing folder contents"
        run: ls
      - uses: actions/checkout@v3

      - name: "login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_LOGIN}}
      - name: "Building docker image"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/myimage .
      - name: "push to Docker hub"
        run: docker push ${{secrets.DOCKER_USERNAME}}/myimage
